# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 512)
        MainWindow.setMinimumSize(QtCore.QSize(421, 512))
        MainWindow.setMaximumSize(QtCore.QSize(421, 512))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 8, 401, 471))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.status_label.setFont(font)
        self.status_label.setStyleSheet("color: rgb(0, 170, 255);")
        self.status_label.setText("")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.field_device = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.field_device.setFrame(True)
        self.field_device.setReadOnly(True)
        self.field_device.setObjectName("field_device")
        self.horizontalLayout.addWidget(self.field_device)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.filter_box = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.filter_box.setEnabled(False)
        self.filter_box.setObjectName("filter_box")
        self.horizontalLayout_3.addWidget(self.filter_box)
        self.clear_filter = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clear_filter.setEnabled(False)
        self.clear_filter.setObjectName("clear_filter")
        self.horizontalLayout_3.addWidget(self.clear_filter)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.list_pkgs = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.list_pkgs.setEnabled(True)
        self.list_pkgs.setSelectionMode(
            QtWidgets.QAbstractItemView.MultiSelection)
        self.list_pkgs.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.list_pkgs.setWordWrap(False)
        self.list_pkgs.setObjectName("list_pkgs")
        self.verticalLayout.addWidget(self.list_pkgs)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_all = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.select_all.setEnabled(False)
        self.select_all.setObjectName("select_all")
        self.horizontalLayout_2.addWidget(self.select_all)
        self.deselect_all = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deselect_all.setEnabled(False)
        self.deselect_all.setObjectName("deselect_all")
        self.horizontalLayout_2.addWidget(self.deselect_all)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.selected_pkgs = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.selected_pkgs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.selected_pkgs.sizePolicy().hasHeightForWidth())
        self.selected_pkgs.setSizePolicy(sizePolicy)
        self.selected_pkgs.setMaximumSize(QtCore.QSize(16777215, 100))
        self.selected_pkgs.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers)
        self.selected_pkgs.setProperty("showDropIndicator", False)
        self.selected_pkgs.setSelectionMode(
            QtWidgets.QAbstractItemView.NoSelection)
        self.selected_pkgs.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.selected_pkgs.setWordWrap(False)
        self.selected_pkgs.setObjectName("selected_pkgs")
        self.verticalLayout.addWidget(self.selected_pkgs)
        self.btn_backup = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_backup.setObjectName("btn_backup")
        self.verticalLayout.addWidget(self.btn_backup)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setIconVisibleInMenu(False)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setIconVisibleInMenu(False)
        self.actionAbout.setPriority(QtWidgets.QAction.HighPriority)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.select_all.clicked.connect(self.list_pkgs.selectAll)
        self.deselect_all.clicked.connect(self.list_pkgs.clearSelection)
        self.clear_filter.clicked.connect(self.filter_box.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate(
                "MainWindow",
                "APyK - Backup android APK"))
        self.label_2.setText(_translate("MainWindow", "Detected device:"))
        self.label.setText(_translate("MainWindow", "Filter packages:"))
        self.clear_filter.setText(_translate("MainWindow", "Clear filter"))
        self.list_pkgs.setSortingEnabled(True)
        self.select_all.setText(_translate("MainWindow", "Select all"))
        self.deselect_all.setText(_translate("MainWindow", "Deselect all"))
        self.selected_pkgs.setSortingEnabled(True)
        self.btn_backup.setText(_translate("MainWindow", "Backup"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
